version: "3.8"
services:
  app:
    build: .
    image: rnium/lungspot
    container_name: lungspot
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000